fun main(){
    println("Set")
    println("Inmutables")
    val numeros = setOf(1,2,1,6,7,8,9,1,1,3)
    println(numeros)
    println("Operaciones de Conjuntos")
    val pares = setOf(2,4,6,8,10)
    println("Pares: $pares")
    val impares = setOf(1,3,5,9)
    val multiplos3 =setOf(3,6,9,12)
    println("Impares: $impares")
    println("Union ${impares union pares}")
    println("interseccion ${impares intersect pares}")
    println("substraccion ${impares subtract multiplos3}")
    println("pares $pares")
    println("impares $impares")
    
    println("----------------------------------")
    println("Set")
    println("Mutables")
    val lenguajes = mutableSetOf("kotlin","java","reactnative")
    println(lenguajes)
    lenguajes.add("kotlin")
    println(lenguajes)
    lenguajes.add("javascript")
    println(lenguajes)
    lenguajes.remove("java")
    println(lenguajes)
    println("Verificar si un valor existe ${"kotlin" in lenguajes}")
    println("Verificar si un valor existe ${"java" in lenguajes}")
}